### ISSUE TITLE
Can't find bundle for base name sun.text.resources.FormatData, locale en_GB

### ISSUE THREAD

**Issue by MatthewHouseman** [ikvmnet/ikvm#173]
I put together a utility using a .Net form using C# that calls a legacy Java application (IKVM bridge) that was packaged up as a JAR file.  Everything works great when all the users run my program on workstations here in the US.
 
When a colleague attempts to use my program in China on a workstation configured for Chinese, they get the following error message:
Can't find bundle for base name sun.text.resources.FormatData, locale en_GB

Is the IKVM distro missing some Java artifact(s) that causes this error?

**Comment by wasabii** [comment]
So, I can't find the issue with this. Looks like FormatData for en_GB is available properly in the develop branch. Haven't checked on main yet. So, whatever the bug was might be fixed.

That said, the best I can do here is try to pull the FormatData for en_GB. I have no idea what your app is doing.

If you could post a unit test or something that would be great.

**Comment by wasabii** [comment]
We have no real way to proceed on this without some sort of test case, or help. And it's not like I can duplicate whatever workstation configuration this guy is using. And it's been stale for a couple months short of a year.

And we're a lot of IKVM versions beyond where we were then. 

Closing. If the problem still exists, hopefully somebody reopens or rereports.
