### ISSUE TITLE
OSX ARM64 Support (Runtime/SDK)

### ISSUE THREAD

**Issue by wasabii** [ikvmnet/ikvm#207]

**Comment by wasabii** [comment]
OSX ARM64 support is only available in .NET 5+. Having ikvmstub and ikvmc available for that platform will be a blocker.

**Comment by chenjing1294** [comment]
@wasabii Are there plans to support osx-x64?

**Comment by wasabii** [comment]
#206

**Comment by schmitch** [comment]
@wasabii is there a reason why it is a blocker to have ikvmstub and ikvmc available on that platform? also I've seen that a lot of code is supported for netcoreapp3.1 is there a reason for that? netcoreapp3.1 is unsupported since december 2022 so I guess moving forward it should target net6.0 since net5.0 is also unsupported:

https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

I mean good that you supported even unsupported versions, but I think there is no reason for that?

**Comment by wasabii** [comment]
The jist of it is that lots of types have moved assemblies in .NET 5 and the code needs a lot of work to make this work both at runtime and static compile time, targeting different frameworks. Right now, we sort of hack around it by looking for types in the netstandard2.0 assembly at static compile time. But this won't work for everything anymore.

One example is System.Collections.Generic.List. It's had various locations over time: mscorlib, netstandard, System.Collections, System.Runtime. it's in System.Private.CoreLib at runtime, but a different assembly at build time.

The ikvmc/ikvmstub code is shared with the IKVM.Runtime code. Using a large amount of IFDEFs. But it's ultimately the same logic. This worked fine in .NET Framework, where everything was piled into mscorlib, whether building at runtime or build time. But now that types are moving around, and different at each, the existing design doesn't quite work right.

**Comment by wasabii** [comment]
Ultimately what we need to do is not make assumptions about what the assembly of a type is, and instead dispatch that logic to some lookup logic which can be swapped out at runtime or build time. But that doesn't exist currently.

**Comment by schmitch** [comment]
ah so that's why there is this whacky error from ikvmc when you run it with just `ikvmc lib.jar` that it fails with "netstandard" could not be found or something. actually for the static ikvmc compiler one would probably need to pass which tfm to target anyway so I'm not sure if it is worth to have a dispatch logic that finds that type on runtime, since that would only work if ikvmc is compiled with `net7` and running under `net7` and the target will be `net7` ? 

I'm pretty sure that since ikvmc works on windows and linux with the `IkvmReference` it's fine the way it is at the moment - I mean moving forward one would just need to say that the target is .net framework or .net6++ since I doubt that moving forward that microsoft will change it again?

**Comment by wasabii** [comment]
No. The types at runtime differ from the types at build time for the same TFM.

And yes they change something every release.

**Comment by wasabii** [comment]
Example: System.Object. The most obvious one.

At runtime, the type is actually "System.Object, System.Private.CoreLib" However, assemblies reference "System.Object, System.Runtime".

**Comment by wasabii** [comment]
I believe this was solved.
