### ISSUE TITLE
Java Service is not Loaded for a Exe project

### ISSUE THREAD

**Issue by realmoieen** [ikvmnet/ikvm#323]
I've created a Library type project called **ProjectLib** which covert the fat jar that contains the **META-INF.services** and output a dll file. In this Library project I added a wrapper class to jar classes So that I can use this C# Lib project into another **EXE** type project. But when I run the **ProjectExe** an Exception occurred.

`
Exception thrown: 'java.util.NoSuchElementException' in IKVM.Java.dll
An unhandled exception of type 'java.util.NoSuchElementException' occurred in IKVM.Java.dll
Unhandled Exception: java.util.NoSuchElementException
   at java.util.ServiceLoader.LazyIterator.nextService()
   at java.util.ServiceLoader.LazyIterator.next()
   at java.util.ServiceLoader.1.next()
   at com.ascertia.test.service.HelloServiceLoader.loadMyHelloService()
   at Com.Ascertia.Test.API.API.sayHelloFromNet(String name)
   at Com.Ascertia.Test.API.Exec.CallAPIFromExe.Main(String[] args)
`
It seems that the services are not loaded when the code is called from exe file.

But When I change my **ProjectLib** type to **EXE** then the META-INF/services are found and the java code is successfully executed. But I don't want to use this approach.

My approach is 
**ProjectLib** use to convert jar to dll and contain some wrapper C# classes 
**ProjectExe** an executable program using **ProjectLib.dll** and **ConvertedJar.dll** as class path dependency

I've created a demo project to reproduce the issue you can check here [Jar-To-Dll-IKVM](https://github.com/realmoieen/Jar-To-Dll-IKVM)

**Comment by wasabii** [comment]
Sounds ClassLoader related. However it's going to depend version much how that Java code is attempting to scan for the file.

By default each converted Assembly is loaded within it's own ClassLoader, of type AssemblyClassLoader, which is smart enough to trace .NET Assembly references when delegating getResources or findClass calls to the AssemblyClassLoader of those other  assemblies.

**Comment by realmoieen** [comment]
I'm using Azul Zulu JDK11 to compile Jdk1.8 target compatible jar file and IKVM 8.4.5 using with net461.

If sounds class loader issue then how this jar works fine when I directly add IkvmReference in an EXE project and use java
classes. 

Does I need to explicitly set JAVA_HOME environment variable or IKVM.Java.dll handle it self.
How this issue can be resolved? Creating a Fat jar is good or I add multiple IkvmReference to convert each dependent jar? Or Can I place jar file as dependency in .Net release so that dependencies jar are loaded directly?

How Can I specify custom class loader in IkvmReference. It there any guide written on this?

**Comment by realmoieen** [comment]
Does the latest IKVM tool contains ikvmc to use manually via command line. I'm new to this tool most of the guide and helping material found on Internet is for older version as i know ikvm is changed as lot in recent years after revive.

**Comment by wasabii** [comment]
>If sounds class loader issue then how this jar works fine when I directly add IkvmReference in an EXE project and use java
classes.

Because that has nothing to do with Java class loaders.

You mentioned this was about using the Service Locator. That DOES have to do with ClassLoaders.

>Does I need to explicitly set JAVA_HOME environment variable or IKVM.Java.dll handle it self.

No. You need to understand how the code you're running works, and what requirements that imposes on you.

To quote myself:

>Sounds ClassLoader related. However it's going to depend version much how that Java code is attempting to scan for the file.

How is the Java code attempting to scan for the file?

>Does the latest IKVM tool contains ikvmc to use manually via command line.

Yes. IkvmReference runs ikvmc.exe. Same thing.

**Comment by realmoieen** [comment]
I've added IkvmReference in .csproj file `
<IkvmReference Include="lib/HelloAbstractService-1.0.jar">
			<AssemblyName>My-Hello-Service-Java</AssemblyName>
			<AssemblyVersion>1.0.0.0</AssemblyVersion>
		</IkvmReference>
      <IkvmReference Include="lib/MyHelloServiceImpl-1.0-all.jar">
			<AssemblyName>My-Hello-Service-Impl-Java</AssemblyName>
			<AssemblyVersion>1.0.0.0</AssemblyVersion>
			<References>lib/HelloAbstractService-1.0.jar</References>
		</IkvmReference>

`
and code using to load the service 
`
ServiceLoader serviceLoader
                = ServiceLoader.load(typeof(com.ascertia.test.service.MyHelloAbstractService), AssemblyClassLoader.getAssemblyClassLoader(Assembly.GetExecutingAssembly()));
            com.ascertia.test.service.MyHelloAbstractService service = (com.ascertia.test.service.MyHelloAbstractService)serviceLoader.iterator().next();
            service.sayHello(name);
`
I've tried the ServiceLoader.load(typeof(com.ascertia.test.service.MyHelloAbstractService)) but the same result.

**Comment by wasabii** [comment]
https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html

>The provider must be accessible from the same class loader that was initially queried to locate the configuration file; note that this is not necessarily the class loader from which the file was actually loaded.

The arguments you pass to ServerLoader.load() matter. Specifically the Class Loader you give it. ServiceLoader.load() is going to query that Class Loader to locate the file (ClassLoader.getResources, specifically). So, this relies very much on the ClassLoader hierarchy that your code is located in.

Normal Java has three 'standard' ClassLoaders: the Bootstrapper, Extension and System. This is true in IKVM too, but only for dynamically loaded classes: those you load directly from a JAR or .class file.

When dealing with statically compiled .NET assemblies, the ClassLoader hierarchy is quite different. Because this is no longer real Java code. All the Java is gone at runtime, and it's a .NET assembly instead. Instead, the default AssemblyClassLoader is used, with internal delegation (no parent), to dispatch requests to delegate class loaders based on the .NET assembly references (as I mentioned earlier).

Imagine you have assembly A. Assembly A has a reference to Assembly B. A reference as in a standard .NET assembly reference. The ClassLoader of classes within Assembly A delegate to the ClassLoader for Assembly B. Java's ClassLoader hierarchy is virtualized to mirror .NET's assembly references. That is, unless your Assembly A has a reference to Assembly B, the ClassLoader for Assembly A will never find Assembly B.

So, if you use `ServiceLocator.load(Class, ClassLoader)`, but you don't pass a ClassLoader in argument 2 which is capable of finding your services resource file, it won't find it. And also according to the documentation, the same ClassLoader must be capable of locating the provider itself.

So, what is GetExecutingAssembly capable of seeing?
