### ISSUE TITLE
NetworkInterface, NullPointerException

### ISSUE THREAD

**Issue by chenjing1294** [ikvmnet/ikvm#379]
version: 8.6.1
platform: windows 10 x64

There will be no error during software debugging, but when the software is released, the operation will report an error：
```
dotnet publish -c Release --runtime win-x64 -p:PublishReadyToRun=true --self-contained true
```
```
System.TypeInitializationException: The type initializer for 'java.net.NetworkInterface' threw an exception.
 ---> java.lang.ExceptionInInitializerError: java.lang.NullPointerException
   --- End of inner exception stack trace ---
   at java.net.NetworkInterface.getNetworkInterfaces()
```

If I post using the command below, there is no problem:
```
dotnet publish -c Release --runtime win10-x64 -p:PublishReadyToRun=true --self-contained true
```

**Comment by wasabii** [comment]
Probably caused because a native library (libjava I'm guessing) is loaded in java.net.NetworkInterface's type initializer somewhere, and the java.dll and other files, during release, are copied into the bin/ directory directly, instead of being nested under runtimes/native. This is an odd property of the .NET SDK. When specifying a RID, the files are moved from runtimes/rid into ./. Might matter for Framework. Doesn't really matter for Core. And forces the app to know both. Also .deps.json is wrong. Totally weird.

That is fixed though. Boot library path now has the path to the IKVM.Runtime.dll included.
