### ISSUE TITLE
The performance is slow

### ISSUE THREAD

**Issue by ShaneHuHu** [ikvmnet/ikvm#630]
Hello Sir

I'm beginer of IKVM, I tried to compile my jar file to C# dll file but I found it's 6 times slower than original java application. I use the <IkvmReference> dotnet4.7.2 project. 

May I ask for some clue about this issue Sir?

Thanks

**Comment by ShaneHuHu** [comment]
I only did some memory operation and write file to  the disk.

**Comment by ShaneHuHu** [comment]
@wasabii May I have a performance report Sir?

**Comment by wasabii** [comment]
A what?

**Comment by ShaneHuHu** [comment]
@wasabii I'm sorry Sir, just I'm curious about performance for normal case. I wonder if my cde is a special case.

**Comment by wasabii** [comment]
I don't have any answers for you. I've not benchmarked anything. Nor compared it to Java. Nor do I know really what your code does.

**Comment by ShaneHuHu** [comment]
@wasabii I'm using scala and I just operate big memory and write a big file. That only thing I'm doing.

**Comment by wasabii** [comment]
I know nothing about Scala.

There are probably at least a dozen different ways to work with files in Java. You could be using java.io. You could be using java.nio.file in synchronous mode. You could be using java.nio.file in asynchronous mode. You could be using selectors. You could be using channels. You could be using RandomAccessFile.

I don't know what "big memory" means. You could be doing stuff against a plain byte array. Or a ByteBuffer. Or a direct byte buffer. Or calling other APIs that implement operations in other ways.

At best I can say if you have some speed issue, try to write a benchmark that demonstrates the issue, and narrows it down to a specific circumstance. And compare it to Java. Report to me which version of OpenJDK you are comparing to. Which OS you are running it on. Beyond that I'm afraid I cannot help with the information I have now.

For the time being I'm going to close this issue because it's pretty inactionable from my perspective.
